---
- hosts: localhost
  connection: local
  become: yes
  vars_files:
    - var/default.yaml

  tasks:
  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Install required system packages for Docker
    apt: name={{ docker_required_packages }} state=latest update_cache=yes

  - name: Add Docker GPG key
    apt_key:
      url: "{{ docker_gpg_url }}"
      state: present

  - name: Add Docker repository
    apt_repository:
      repo: "{{ docker_repo }}"
      state: present

  - name: Install Docker
    apt: name={{ docker_packges }} state=latest update_cache=yes

  - name: Install Python Docker module
    pip:
      name: docker

  - name: Add adminstrator to docker group
    user:
      name: "{{ admin_user }}"
      groups: docker
      append: yes

  - name: Install Docker Compose
    get_url:
      url: "{{ docker_compose_url }}"
      dest: /usr/local/bin/docker-compose
      mode: u+x,g+x,o+x

  - name: Install python-psutil package
    apt: name=python3-psutil

  - name: Copy wallpaper file
    copy: src=desktop/test.jpg dest=/home/gorel/.test.jpg

  - name: Set GNOME Wallpaper
    become_user: "{{ admin_user }}"
    dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///home/gorel/.test.jpg'"

  - name: Set GNOME Wallpaper scale
    become_user: "{{ admin_user }}"
    dconf: key="/org/gnome/desktop/background/picture-options" value="'scaled'"

  - name: Install Vagrant
    apt: name=vagrant

  - name: Set GPG for VScode
    apt_key:
      url: "{{ vs_gpg_url }}"
      state: present

  - name: add VScode repo
    apt_repository:
      repo: "{{ vs_repo }}"
      state: present

  - name: install VScode
    apt: name=code
